---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      all:
        patterns:
          - "*"      
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      patch-updates:
        update-types:
          - "patch"
        exclude-patterns:
          - "jakarta.*"
      minor-updates:
        update-types:
          - "minor"
        exclude-patterns:
          - "jakarta.*"
  - package-ecosystem: "docker"
    directory: "/docker-compose"
    schedule:
      interval: "daily"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "terraform"
    directory: "/infrastructure/terraform"
    schedule:
      interval: "daily"
    groups:
      all:
        patterns:
          - "*"
