---
version: "3"

services:

  fakebank:
    container_name: fakebank
    build:
      context: .
      dockerfile: docker-compose/Dockerfile.fakebank
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: database
    build:
      context: .
      dockerfile: docker-compose/Dockerfile.database
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: fakebank
    volumes:
      - ./fakebank-impl/src/main/resources/db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    healthcheck:
      test: [ "CMD","mysqladmin","ping","-h","localhost" ]
      timeout: 10s
      retries: 10
