spring:
  mustache:
    check-template-location: false
zuul:
  routes:
    accounts:
      path: /accounts/**
      url: http://localhost:8080/accounts
    payment:
      path: /payment/**
      url: http://localhost:8080/payment